# Generated by Django 2.0 on 2017-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'under updating'), (3, 'under maintaining'), (4, ' failed')], db_index=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='version',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='servers',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'failed'), (3, 'under deploying'), (4, 'under maintaining')], db_index=True),
        ),
    ]
