# Generated by Django 2.0 on 2017-12-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20171219_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(db_index=True, verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'under updating'), (3, 'under maintaining'), (4, ' failed'), (5, 'just created')], db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(db_index=True, verbose_name='date published')),
                ('updated', models.DateTimeField(verbose_name='date published')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'failed'), (3, 'under deploying'), (4, 'under maintaining'), (5, 'just created')], db_index=True)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='hosted_on',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.AddField(
            model_name='client',
            name='hosted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Server'),
        ),
        migrations.AddField(
            model_name='client',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Version'),
        ),
    ]
