version: '2'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'mseuser'
      POSTGRES_PASSWORD: 'msepass'
      POSTGRES_DB: 'mse'
    restart: always


  mse:
    build:
        context: ./
        dockerfile: ./mse.Dockerfile
    image: django_image
    restart: always
    depends_on:
      - db

  nginx:
    build:
        context: ./
        dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    restart: always

  redis:
    image: redis:4.0.6
    restart: always

  celery:
    image: celery:4.0.2
    restart: always
    depends_on:
      - redis
