# Generated by Django 2.0 on 2017-12-22 09:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 42, 52, 829209, tzinfo=utc), verbose_name='date created')),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 12, 22, 9, 42, 52, 829260, tzinfo=utc), verbose_name='date updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'under updating'), (3, 'under maintaining'), (4, ' failed'), (5, 'just created')], db_index=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 42, 52, 826820, tzinfo=utc), verbose_name='date published')),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 12, 22, 9, 42, 52, 826878, tzinfo=utc), verbose_name='date published')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'operate'), (2, 'failed'), (3, 'under deploying'), (4, 'under maintaining'), (5, 'just created')], db_index=True, default=5)),
                ('info', models.CharField(max_length=500)),
                ('action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'start server'), (0, 'stop server'), (2, 'deploy server'), (3, 'send to maintain'), (4, 'delete server')], db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'deprecated version'), (1, 'under development'), (2, 'under testing'), (3, 'producation ready')], db_index=True, default='1')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 42, 52, 782214, tzinfo=utc), verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='hosted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Server'),
        ),
        migrations.AddField(
            model_name='client',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Version'),
        ),
    ]
