# Generated by Django 2.0 on 2017-12-22 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 44, 25, 769905, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 9, 44, 25, 769944, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'start server'), (0, 'stop server'), (2, 'deploy server'), (3, 'send to maintain'), (4, 'delete server')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 44, 25, 769278, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 9, 44, 25, 769311, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='version',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 9, 44, 25, 756931, tzinfo=utc), verbose_name='date created'),
        ),
    ]
