# Generated by Django 2.0 on 2017-12-22 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20171222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 13, 59, 37, 864360, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 13, 59, 37, 864402, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'start server'), (0, 'stop server'), (2, 'deploy server'), (3, 'send to maintain'), (4, 'delete server'), (5, 'none')], db_index=True, default=5),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 13, 59, 37, 863709, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 13, 59, 37, 863747, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='version',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 22, 13, 59, 37, 852301, tzinfo=utc), verbose_name='date created'),
        ),
    ]
