# Generated by Django 2.0 on 2017-12-21 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20171221_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'deprecated version'), (1, 'under development'), (2, 'under testing'), (3, 'producation ready')], db_index=True, default='1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 21, 15, 18, 49, 523773, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'under updating'), (3, 'under maintaining'), (4, ' failed'), (5, 'just created')], db_index=True, default=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 18, 49, 523806, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 21, 15, 18, 49, 523002, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'stopped'), (1, 'started'), (2, 'failed'), (3, 'under deploying'), (4, 'under maintaining'), (5, 'just created')], db_index=True, default=5),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 18, 49, 523042, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='version',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 12, 21, 15, 18, 49, 496452, tzinfo=utc), verbose_name='date created'),
        ),
    ]
